# fly.toml app configuration file generated for meditation-app on 2024-12-19T10:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "meditation-app"
primary_region = "nrt"

[build]

[env]
  PORT = "8080"
  RAILS_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"
  RAILS_LOG_TO_STDOUT = "true"
  RAILS_MASTER_KEY = "918b0e9b8224d6e86f66e4f3adb67f67"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "meditation_app_data"
  destination = "/rails/storage"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"
    grace_period = "60s"
    restart_limit = 0

  [[services.http_checks]]
    grace_period = "120s"
    interval = "30s"
    method = "GET"
    timeout = "15s"
    path = "/health"
    protocol = "http"
    tls_skip_verify = true

# PostgreSQLアドオンは別途設定が必要
# fly postgres create --name meditation-app-db --region nrt
# fly postgres attach meditation-app-db --app meditation-app 